# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: strm/helloworld-http
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: hello-service
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: false
