apiVersion: v1
kind: Pod
metadata:
  name: mandatory-name
  labels:
    name: hello-world-pod 
spec:
  containers:
  - name: hi
    image: strm/helloworld-http
    ports: 
    - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  ports: 
  - port: 80
  selector: 
    name: hello-world-pod