apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world-deployment
    spec:
      containers:
      - name: hi
        image: strm/helloworld-http
        ports: 
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  ports: 
  - port: 80
  selector: 
    name: hello-world-deployment